In [11]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

X, y = load_iris(return_X_y=True)          # 150 Blüten, 4 Merkmale
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1
)
model = KNeighborsClassifier(n_neighbors=5) # Klasse/Zielgröße wird anhand von Nachbarn bestimmt 

model.fit(X_train, y_train)                # lernen

# Vorhersage
print(model.predict(X_test[:5]))           # -> [0 1 1 0 2]

# Echte Daten 
print(y_test[:5])                          # -> [0 1 1 0 2]
print(model.score(X_test, y_test))         # Genauigkeit 



[0 1 1 0 2]
[0 1 1 0 2]
1.0


In [17]:
model.kneighbors(X_test)

(array([[0.54772256, 0.55677644, 0.58309519, 0.59160798, 0.65574385],
        [0.38729833, 0.38729833, 0.72111026, 0.79372539, 0.81853528],
        [0.14142136, 0.24494897, 0.26457513, 0.31622777, 0.34641016],
        [0.34641016, 0.36055513, 0.41231056, 0.45825757, 0.45825757],
        [0.41231056, 0.88317609, 0.92736185, 0.93273791, 1.06301458],
        [0.37416574, 0.42426407, 0.45825757, 0.45825757, 0.46904158],
        [0.24494897, 0.36055513, 0.46904158, 0.50990195, 0.51961524],
        [0.36055513, 0.41231056, 0.47958315, 0.5       , 0.50990195],
        [0.14142136, 0.17320508, 0.2236068 , 0.2236068 , 0.24494897],
        [0.2236068 , 0.26457513, 0.3       , 0.3       , 0.36055513],
        [0.2236068 , 0.3       , 0.31622777, 0.33166248, 0.33166248],
        [0.33166248, 0.34641016, 0.36055513, 0.38729833, 0.41231056],
        [0.41231056, 0.45825757, 0.5       , 0.51961524, 0.53851648],
        [0.34641016, 0.37416574, 0.38729833, 0.41231056, 0.42426407],
        [0.2       ,

In [7]:
X[0], y[0]
X[50], y[50]
X[100], y[100]

(array([6.3, 3.3, 6. , 2.5]), np.int64(2))